serviceboot:
  python_version: 3.7.8
  cname: 测试代码
  ename: test-demo
  version: 1.0.0
  port:
    dev: 3330
    prod: 3330   # default: 80. 若部署至CubeAI，端口号应固定为3330.
  has_web: yes  # default: no
  compile_python: no  # default: no
  process_num: 1  # default: 1. 值为0时进程数等于当前主机CPU核数